PACKAGE_NAME="smifb"
PACKAGE_VERSION="2.4.2"
AUTOINSTALL="yes"
MAKE[0]="make DKMS_BUILD=1 KVER=${kernelver}"
CLEAN="make clean DKMS_BUILD=1 KVER=${kernelver}"
BUILT_MODULE_NAME[0]="smifb"
DEST_MODULE_LOCATION[0]="/updates"